[package]
name = "less5"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.7"
cargo-watch = "8.5.3"
json = "0.12.4"
serde = "1.0.228"
serde_json = "1.0.145"
tokio = { version = "1.48.0", features = ["macros", "rt-multi-thread"] }
